### ISSUE TITLE
Add framework to repo?

### ISSUE THREAD

**Issue by esauter5** [carnivalmobile/carnival-sdk-react-native#1]
Is there any reason the embedded framework isn't included in this repo?. It would save the step of separately having to download from https://github.com/carnivalmobile/carnival-ios-sdk/releases. I'd be happy to submit a PR, if you're onboard with this.

**Comment by samjarman** [comment]
Hey! 

Yes, two reasons.

1) If you get the latest version, then you'll have the latest bug fixes and features. 
2) If we were to include and distribute via NPM, the compression process that NPM uses would break the symlinks inside the .embeddedframework file. 

Happy to hear if you have any ideas to get around these? :)

**Comment by esauter5** [comment]
Good to know. I wasn't aware of 2. If that's the case, I don't have any other ideas here. I may do some digging later if I get a chance, but I'll close the issue for now. Thanks again for the great work here. I started rolling my own RN module for another PN provider I was using and it's awesome to see you guys have one :)
