### ISSUE TITLE
V2.0.0 has not been published to npm

### ISSUE THREAD

**Issue by clickclickonsal** [carnivalmobile/carnival-sdk-react-native#15]
Hey I saw you pushed a fix for issue #5. Thanks for that! 😄 I ran into a issue trying to switch back to your package & noticed that 2.0.0 isn't in npm. Would you care to publish it? 😄

**Comment by igstewart3** [comment]
Hey, sorry about that (and for getting back to you so much later). V2.0.0 is now on npm, as is V2.2.0 if you want the latest and greatest. Cheers for pointing out it was missing!
