### ISSUE TITLE
IOS Build problem

### ISSUE THREAD

**Issue by matc4** [carnivalmobile/carnival-sdk-react-native#3]
Hi, i'm having problems for building in IOS

> CarnivalReactNativePlugin.m:28:13: No known class method for selector 'startEngine:registerForPushNotifications:ignoreAutoAnalyticsSources:'

I resolve this issue removing ignoreAutoAnalyticsSources

`RCT_EXPORT_METHOD(startEngine:(NSString *)key registerForPushNotifications:(BOOL)registerForPushNotifications) {
    [Carnival startEngine:key registerForPushNotifications:registerForPushNotifications ];  
}`

React Native: 0.35.0
XCode: 8.1

**Comment by samjarman** [comment]
This should be fixed in the latest version @matc4 :) Re-open this issue if the problem persists.
