### ISSUE TITLE
Error: Redefinition of RCTMethodInfo

### ISSUE THREAD

**Issue by clickclickonsal** [carnivalmobile/carnival-sdk-react-native#5]
I'm running react-native version 0.55.4 & since implementing this library I can't get it to build for iOS on xcode. I get the error `Error: Redefinition of RCTMethodInfo`. I was able to get it to finally build by removing the conditional in the [RNCarinval.h](https://github.com/carnivalmobile/carnival-sdk-react-native/blob/master/ios/RNCarnival.h) file & it just be
```
#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>
```

Since I'm not to familiar with ios code so idk if that's the right solution but if it, the I'm happy to submit a PR to take care of this.

**Comment by igstewart3** [comment]
Thanks for pointing this out, I've made the change in RNCarnival.h.

**Comment by clickclickonsal** [comment]
Awesome! Thank you! 🙏
