### ISSUE TITLE
D8: Program type already present: com.reactlibrary.BuildConfig

### ISSUE THREAD

**Issue by matt-dalton** [carnivalmobile/carnival-sdk-react-native#51]
I'm getting this error when I try and build on Android.

From Googling around, it looks like this is becase the package name in https://github.com/carnivalmobile/carnival-sdk-react-native/blob/master/android/src/main/AndroidManifest.xml is named generically, and is clashing with another of my dependencies.

See the same issue on other libraries [here](https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/8) and [here](https://github.com/rumax/react-native-PDFView/issues/61).

Would it be possible to rename this to something less generic?

**Comment by igstewart3** [comment]
Hi Matt, thanks for bringing this to my attention. That package clash isn't ideal, I'll organise repackaging the Android code to avoid it. It should be included in the next release of the SDK.

**Comment by matt-dalton** [comment]
Thanks @igstewart3!

Do you know if this will be relatively soon? Just would like to get an idea of whether to wait or implement my own patch/fork.

**Comment by igstewart3** [comment]
I've got some other changes that I'm planning to do a release for shortly, all things being well it should hopefully be out in the next week.
