### ISSUE TITLE
Errors when adding additional options to SDK on iOS

### ISSUE THREAD

**Issue by matt-dalton** [carnivalmobile/carnival-sdk-react-native#53]
I've managed to get my iOS project to build, but am struggling with getting the [additional options configuration](https://docs.mobile.sailthru.com/docs/react-native-integration#section-additional-options) to work. It's likely partly my unfamiliarity with Objective-C that's the problem, but there's something in the instructions that doesn't seem to be working for me.

Here's my code (I've tried to merge the additional options instructions with the basic setup):

```
id<RCTBridgeDelegate> moduleInitialiser = [[RNSailthruMobileBridge alloc] 
                                              initWithJSCodeLocation:jsCodeLocation 
                                              appKey:sailthruToken
                                              pushAuthorizationOption: STMPushAuthorizationOptionNoRequest ];

moduleInitialiser.displayInAppNotifications = NO
  
  
RCTBridge * bridge = [[RCTBridge alloc] initWithDelegate:moduleInitialiser launchOptions:launchOptions];


RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                      moduleName:@"MY_MODULE"
                                               initialProperties:initialProperties];
```

However I'm getting two errors in Xcode:
`No visible @interface for 'RNSailthruMobileBridge' declares the selector 'initWithJSCodeLocation:appKey:pushAuthorizationOption:'`

`Property 'displayInAppNotifications' not found on object of type '__strong id<RCTBridgeDelegate>'`

Is it possible to be a bit clearer about how to integrate the two sets of instructions?

**Comment by igstewart3** [comment]
It looks like your initialiser method call is missing the `geoIpTrackingDefault:` parameter, which is why Xcode can't find the selector.

Your `id<RCTBridgeDelegate>` doesn't know that it is an `RNSailthruMobileBridge` object, which is why it can't find `displayInAppNotifications`. You can either wrap the call in a cast:
`((RNSailthruMobileBridge*)moduleInitialiser).displayInAppNotifications = NO`

or you can make `moduleInitialiser` an RNSailthruMobileBridge instance:
`RNSailthruMobileBridge* moduleInitialiser = [[RNSailthruMobileBridge alloc] 
                                              initWithJSCodeLocation:jsCodeLocation 
                                              appKey:sailthruToken
                                              pushAuthorizationOption: STMPushAuthorizationOptionNoRequest
                                              geoIpTrackingDefault:YES];`

**Comment by matt-dalton** [comment]
Ahh great. For anyone else looking, the final code that worked (thanks to your advice) was:

```
RNSailthruMobileBridge* moduleInitialiser = [[RNSailthruMobileBridge alloc] 
                                              initWithJSCodeLocation:jsCodeLocation 
                                              appKey:sailthruToken
                                              pushAuthorizationOption: STMPushAuthorizationOptionNoRequest
                                              geoIpTrackingDefault:YES];

moduleInitialiser.displayInAppNotifications = NO;
  
  
RCTBridge * bridge = [[RCTBridge alloc] initWithDelegate:moduleInitialiser launchOptions:launchOptions];


RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                      moduleName:@"MY_MODULE"
                                               initialProperties:initialProperties];
```

One tiny thing you should fix in the docs [here]([url](https://docs.mobile.sailthru.com/docs/react-native-integration#section-additional-options)), is the comma after `pushAuthorizationOption: STMPushAuthorizationOptionNoRequest,`. That was causing a final issue for me and confusing things.

**Comment by igstewart3** [comment]
Awesome, glad to hear you've got it working. I'll remove that comma from the docs and mark this issue as closed.
