### ISSUE TITLE
Sailthru SDK cannot decrypt link

### ISSUE THREAD

**Issue by high-performance-hery** [carnivalmobile/carnival-sdk-react-native#81]
We've found a recent issue where deeplinks cannot be decrypted by the Sailthru SDK anymore.

The issue is that the encrypted link comes in the format e.g.

> https://link.domain.com/click/28364378.289118/aHc..yM/5e6/email

If we remove the `/email` part at the end, then the link can be decrypted.

This might be an issue on Sailthru's end when encrypting the link, or an issue with the SDK.
It's hard to tell but it doesn't look like we're modifying the encrypted link at any time.

**Comment by igstewart3** [comment]
This issue is resolved in [v8.0.0](https://github.com/carnivalmobile/carnival-sdk-react-native/releases/tag/v8.0.0)
